### PR TITLE
CardPricingPlan2 PR

### PR DESCRIPTION
**Pull request by kevintruo**
Hi @siriwatknp,

I have re-created the CardPricingPlan2. Can you take a look when you have a chance?

### CODE REVIEW

**Comment by siriwatknp** [comment]
Oh, wow 👏. Sorry for the delay

**Review by siriwatknp — APPROVED** [review]
👍 Thanks for your contribution!

**Comment by kevintruo** [comment]
> 👍 Thanks for your contribution!

No problem! Feel free to open an issue on a design that you'd like, I'll take a look on my free time.

**Comment by siriwatknp** [comment]
@all-contributors please add @kevintruo  for code

**Pull request merged**
